Areas/AddnlArea/Controllers/RapidiController.cs
using coremvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace coremvc.Area.AddnlArea.Controllers
{
    [Area("AddnlArea")]
    public class RapidiController : Controller
    {
        public IActionResult Index()
        {
            List<Student> st = new List<Student>()
            {
                new Student()
                {
                    roll=1, name="kaka", gender="Male", age=32, dob = new DateTime(2000,09,02),course="MPC",
                },
                new Student()
                {
                    roll=2, name="kanta", gender="FeMale", age=35, dob = new DateTime(2005,01,12),course="MPC",
                },
                new Student()
                {
                    roll=3, name="gaddi", gender="FeMale", age=38, dob = new DateTime(2001,01,06),course="MPC",
                },
                new Student()
                {
                    roll=4, name="beda", gender="Male", age=89, dob = new DateTime(2002,04,02),course="MPC",
                },
                new Student()
                {
                    roll=5, name="poolu", gender="Male", age=69, dob = new DateTime(2003,03,02),course="MPC",
                }

            };
            return View(st);
        }
        public IActionResult Create()
        {

            return View();
        }
        public IActionResult Rapidi()
        {
            return View();
        }
    }
}

Areas/AddnlArea/Views/Rapidi/Create.cshtml
@model coremvc.Models.Student

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create";
}

<h1>Add Data For Student</h1>

<h4>Student Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="roll" class="control-label"></label>
                <input asp-for="roll" class="form-control" />
                <span asp-validation-for="roll" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <input asp-for="gender" class="form-control" />
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="course" class="control-label"></label>
                <input asp-for="course" class="form-control" />
                <span asp-validation-for="course" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dob" class="control-label"></label>
                <input asp-for="dob" class="form-control" />
                <span asp-validation-for="dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="age" class="control-label"></label>
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fee" class="control-label"></label>
                <input asp-for="fee" class="form-control" />
                <span asp-validation-for="fee" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="/AddnlArea/Rapidi/Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/AddnlArea/Views/Rapidi/Index.cshtml
@model IEnumerable<coremvc.Models.Student>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    @* <a asp-area="AddnlArea" asp-controller="Rapidi" asp-action="Create">Create New</a> *@
    <a href="/AddnlArea/Rapidi/Create">Create New</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.roll)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dob)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fee)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.roll)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.course)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fee)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.roll  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.roll  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.roll  })
            </td>
        </tr>
}
    </tbody>
</table>

Areas/AddnlArea/Views/Rapidi/Rapidi.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Rapidi Page";

}

<div class="text-center">
    <h1 class="display-4">View in the Area</h1>
    <h3>Welcome to Area View Rapidi</h3>
    
    
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>